/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

const Book = IDL.Record({
  id: IDL.Nat,
  name: IDL.Text,
  uploadedAt: IDL.Int,
  totalSegments: IDL.Nat,
});

const Segment = IDL.Record({
  id: IDL.Nat,
  bookId: IDL.Nat,
  chapterIndex: IDL.Nat,
  chapterTitle: IDL.Text,
  pageNumber: IDL.Nat,
  content: IDL.Text,
});

const SearchResult = IDL.Record({
  segment: Segment,
  snippet: IDL.Text,
});

const ChapterInfo = IDL.Record({
  index: IDL.Nat,
  title: IDL.Text,
  segmentCount: IDL.Nat,
});

const Flashcard = IDL.Record({
  question: IDL.Text,
  answer: IDL.Text,
});

const SegmentInput = IDL.Record({
  chapterIndex: IDL.Nat,
  chapterTitle: IDL.Text,
  pageNumber: IDL.Nat,
  content: IDL.Text,
});

export const idlService = IDL.Service({
  createBook: IDL.Func([IDL.Text], [IDL.Nat], []),
  listBooks: IDL.Func([], [IDL.Vec(Book)], ['query']),
  getBook: IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
  deleteBook: IDL.Func([IDL.Nat], [IDL.Bool], []),
  addSegments: IDL.Func([IDL.Nat, IDL.Vec(SegmentInput)], [IDL.Bool], []),
  searchBook: IDL.Func([IDL.Nat, IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  getChapters: IDL.Func([IDL.Nat], [IDL.Vec(ChapterInfo)], ['query']),
  getChapterSegments: IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Segment)], ['query']),
  getChapterSummary: IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], ['query']),
  getFlashcards: IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Flashcard)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Book = IDL.Record({
    id: IDL.Nat,
    name: IDL.Text,
    uploadedAt: IDL.Int,
    totalSegments: IDL.Nat,
  });
  const Segment = IDL.Record({
    id: IDL.Nat,
    bookId: IDL.Nat,
    chapterIndex: IDL.Nat,
    chapterTitle: IDL.Text,
    pageNumber: IDL.Nat,
    content: IDL.Text,
  });
  const SearchResult = IDL.Record({
    segment: Segment,
    snippet: IDL.Text,
  });
  const ChapterInfo = IDL.Record({
    index: IDL.Nat,
    title: IDL.Text,
    segmentCount: IDL.Nat,
  });
  const Flashcard = IDL.Record({
    question: IDL.Text,
    answer: IDL.Text,
  });
  const SegmentInput = IDL.Record({
    chapterIndex: IDL.Nat,
    chapterTitle: IDL.Text,
    pageNumber: IDL.Nat,
    content: IDL.Text,
  });
  return IDL.Service({
    createBook: IDL.Func([IDL.Text], [IDL.Nat], []),
    listBooks: IDL.Func([], [IDL.Vec(Book)], ['query']),
    getBook: IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
    deleteBook: IDL.Func([IDL.Nat], [IDL.Bool], []),
    addSegments: IDL.Func([IDL.Nat, IDL.Vec(SegmentInput)], [IDL.Bool], []),
    searchBook: IDL.Func([IDL.Nat, IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    getChapters: IDL.Func([IDL.Nat], [IDL.Vec(ChapterInfo)], ['query']),
    getChapterSegments: IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Segment)], ['query']),
    getChapterSummary: IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], ['query']),
    getFlashcards: IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Flashcard)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
