/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  id: bigint;
  name: string;
  uploadedAt: bigint;
  totalSegments: bigint;
}
export interface Segment {
  id: bigint;
  bookId: bigint;
  chapterIndex: bigint;
  chapterTitle: string;
  pageNumber: bigint;
  content: string;
}
export interface SearchResult {
  segment: Segment;
  snippet: string;
}
export interface ChapterInfo {
  index: bigint;
  title: string;
  segmentCount: bigint;
}
export interface Flashcard {
  question: string;
  answer: string;
}
export interface SegmentInput {
  chapterIndex: bigint;
  chapterTitle: string;
  pageNumber: bigint;
  content: string;
}

export interface _SERVICE {
  createBook: ActorMethod<[string], bigint>;
  listBooks: ActorMethod<[], Book[]>;
  getBook: ActorMethod<[bigint], [] | [Book]>;
  deleteBook: ActorMethod<[bigint], boolean>;
  addSegments: ActorMethod<[bigint, SegmentInput[]], boolean>;
  searchBook: ActorMethod<[bigint, string], SearchResult[]>;
  getChapters: ActorMethod<[bigint], ChapterInfo[]>;
  getChapterSegments: ActorMethod<[bigint, bigint], Segment[]>;
  getChapterSummary: ActorMethod<[bigint, bigint], string>;
  getFlashcards: ActorMethod<[bigint, bigint], Flashcard[]>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
