/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return { __kind__: "Some", value };
}
function none(): None {
    return { __kind__: "None" };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) throw new Error("unwrap: none");
    return option.value;
}

export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null) {
        if (blob) this._blob = blob;
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([new Uint8Array(blob)], { type: 'application/octet-stream' }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) return this._blob;
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}

export interface backendInterface {
    createBook(name: string): Promise<bigint>;
    listBooks(): Promise<any[]>;
    getBook(bookId: bigint): Promise<any>;
    deleteBook(bookId: bigint): Promise<boolean>;
    addSegments(bookId: bigint, segments: any[]): Promise<boolean>;
    searchBook(bookId: bigint, query: string): Promise<any[]>;
    getChapters(bookId: bigint): Promise<any[]>;
    getChapterSegments(bookId: bigint, chapterIndex: bigint): Promise<any[]>;
    getChapterSummary(bookId: bigint, chapterIndex: bigint): Promise<string>;
    getFlashcards(bookId: bigint, chapterIndex: bigint): Promise<any[]>;
}

export class Backend implements backendInterface {
    private actor: ActorSubclass<_SERVICE>;
    private processError?: (error: unknown) => never;

    constructor(
        actor: ActorSubclass<_SERVICE>,
        _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
        _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
        processError?: (error: unknown) => never
    ) {
        this.actor = actor;
        this.processError = processError;
    }

    private async call<T>(fn: () => Promise<T>): Promise<T> {
        try {
            return await fn();
        } catch (e) {
            if (this.processError) return this.processError(e);
            throw e;
        }
    }

    createBook(name: string): Promise<bigint> {
        return this.call(() => (this.actor as any).createBook(name));
    }
    listBooks(): Promise<any[]> {
        return this.call(() => (this.actor as any).listBooks());
    }
    getBook(bookId: bigint): Promise<any> {
        return this.call(async () => {
            const result = await (this.actor as any).getBook(bookId);
            // Candid Opt returns [] or [value] - convert to Option shape
            if (Array.isArray(result)) {
                if (result.length === 0) return { __kind__: "None" };
                return { __kind__: "Some", value: result[0] };
            }
            return result;
        });
    }
    deleteBook(bookId: bigint): Promise<boolean> {
        return this.call(() => (this.actor as any).deleteBook(bookId));
    }
    addSegments(bookId: bigint, segments: any[]): Promise<boolean> {
        return this.call(() => (this.actor as any).addSegments(bookId, segments));
    }
    searchBook(bookId: bigint, query: string): Promise<any[]> {
        return this.call(() => (this.actor as any).searchBook(bookId, query));
    }
    getChapters(bookId: bigint): Promise<any[]> {
        return this.call(() => (this.actor as any).getChapters(bookId));
    }
    getChapterSegments(bookId: bigint, chapterIndex: bigint): Promise<any[]> {
        return this.call(() => (this.actor as any).getChapterSegments(bookId, chapterIndex));
    }
    getChapterSummary(bookId: bigint, chapterIndex: bigint): Promise<string> {
        return this.call(() => (this.actor as any).getChapterSummary(bookId, chapterIndex));
    }
    getFlashcards(bookId: bigint, chapterIndex: bigint): Promise<any[]> {
        return this.call(() => (this.actor as any).getFlashcards(bookId, chapterIndex));
    }
}

export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}

export function createActor(
    canisterId: string,
    _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
    _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
    options: CreateActorOptions = {}
): Backend {
    const agent = options.agent || HttpAgent.createSync({ ...options.agentOptions });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId,
        ...options.actorOptions,
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
